Creating MainVC (Tracker) with TabBar and Logic
DanteIT94/DailyTrackerApp pull request #1
Opened 2023-06-21 09:05 UTC by DanteIT94

2023-07-07 17:10 UTC, protos17 requested changes

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TabBar/TabBarViewConroller.swift
> +
Здесь необходимо установить цвет:

view.backgroundColor = .white

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TabBar/TabBarViewConroller.swift
> +        tabBar.tintColor = .white
А здесь убрать, он не должен быть белым

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/Helpers/MockHelpers .swift
> +                Tracker(id: UUID(), name: "Этил", color: .colorSection5 ?? .green, emoji: "❤️", schedule: [0, 1, 2, 3, 4, 5, 6, 7]),
Старайся упростить такие действия, массив последовательных чисел можно указать как:

Array(0...7)

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/Models/Tracker.swift
> +    ///Можно ли заменить на UUID?
У тебя он и так UUID

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/CategoryFolder/CategoryCell.swift
> +//    private let arrowImageView: UIImageView = {
Лишний закомментированный код рекомендую удалять

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/CategoryFolder/CategoryViewController.swift
> +        if categoryArray.count != 0 {
Можно заменить на:

!categoryArray.isEmpty

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/CategoryFolder/CategoryViewController.swift
> +    @objc func addCategoryButtonTapped() {
Для @objc также рекомендую указывать как private чтобы спрятать детали реализации конкретной части функциональности, когда они используются только внутри области объявления

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/CategoryFolder/CategoryViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: CategoryCell.reuseIdentifier, for: indexPath) as! CategoryCell
Рекомендую не использовать принудительное извлечение опционалов

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/CategoryFolder/NewCategoryViewController.swift
> +    weak var delegate: NewCategoryViewControllerDelegate?
Публичные свойства принято писать перед приватными

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/CategoryFolder/NewCategoryViewController.swift
> +    @objc func readyButtonTapped() {
Рекомендую указать как private

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/NewHabitCreation/NewHabitViewController.swift
> +    @objc func createHabitButtonTapped() {
Рекомендую везде по проекту @objc методы указать как private

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/NewHabitCreation/NewHabitViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: NewHabitCell.reuseIdentifier, for: indexPath) as! NewHabitCell
Рекомендую сделать проверку через guard let

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/NewHabitCreation/NewHabitViewController.swift
> +//    //MARK: -Доделать чуть позже
Рекомендую места для доделываний указывать как:

//TODO: -

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/ScheduleFolder/ScheduleViewController.swift
> +            }
Можно упростить:

switchStates[index] = finalList.contains(weekdayIndex + 1)

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/ScheduleFolder/ScheduleViewController.swift
> +                guard let weekday = getIndexOfWeek(text) else { continue }
Несколько условий guard можно писать просто через запятую:

guard cell.switcher.isOn,
let text = cell.textLabel?.text else { continue }

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/ScheduleFolder/ScheduleViewController.swift
> +//import UIKit
Рекомендую удалить

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/ScheduleFolder/SwitchCell.swift
> +    func switchCellDidToggle(_ cell: SwitchCell, isOn: Bool)
Рекомендую var switcher: UISwitch тоже указать в протоколе

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/TrackerTypeViewController.swift
> +        //        nonRegularEventButton.addTarget(nil, action: #selector(nonRegularEventButtonTapped), for: .touchUpInside)
Необходимо добавить функциональность добавления нерегулярного события

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerViewFolder/TrackerCardViewCell.swift
> +        }
Они тоже входят в условие .default

2023-07-07 17:10 UTC, protos17 commented on ToDoTracker/TrackerViewFolder/TrackersViewController.swift
> +        }
Рекомендую выровнять код

2023-07-09 10:02 UTC, protos17 requested changes

2023-07-09 10:02 UTC, protos17 commented on ToDoTracker/TrackerViewFolder/TrackerCardViewCell.swift
> +    func dayCheckButtonState() {
Рекомендую указать как private

2023-07-09 10:02 UTC, protos17 commented on ToDoTracker/TrackerViewFolder/TrackerCardViewCell.swift
> +    func dayCheckButtonIsEnabled() {
Рекомендую указать как private

2023-07-09 10:02 UTC, protos17 commented on ToDoTracker/TrackerViewFolder/TrackerCardViewCell.swift
> +    @objc func dayCheckButtonTapped(_ sender: UIButton) {
Рекомендую указать как private

2023-07-09 10:02 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/NewHabitCreation/NewHabitViewController.swift
> +        if habitTextField.text?.isEmpty == false,
Можно не указывать true и false:

!habitTextField.text?.isEmpty

2023-07-09 10:52 UTC, DanteIT94 commented on ToDoTracker/TrackerCreationViewFolder/NewHabitCreation/NewHabitViewController.swift
> +        if habitTextField.text?.isEmpty == false,
надаюсь с опытом придет понимание где можно "срезать" синтаксис)  Спасибо за уточнение!

2023-07-09 11:00 UTC, DanteIT94 commented on ToDoTracker/TrackerCreationViewFolder/NewHabitCreation/NewHabitViewController.swift
> +        if habitTextField.text?.isEmpty == false,
пришлось развернуть чтобы !habitTextField.text?.isEmpty заработал(

2023-07-09 11:00 UTC, DanteIT94 commented on ToDoTracker/TrackerViewFolder/TrackerCardViewCell.swift
> +    @objc func dayCheckButtonTapped(_ sender: UIButton) {
Поправил

2023-07-09 11:01 UTC, DanteIT94 commented on ToDoTracker/TrackerViewFolder/TrackerCardViewCell.swift
> +    func dayCheckButtonIsEnabled() {
Поправил

2023-07-09 11:04 UTC, DanteIT94 commented on ToDoTracker/TrackerViewFolder/TrackerCardViewCell.swift
> +    func dayCheckButtonState() {
Поправил

2023-07-09 11:07 UTC, DanteIT94 commented on ToDoTracker/TrackerViewFolder/TrackerCardViewCell.swift
> +        }
Я когда думал как это написать тоже так думал) Но оказалось что у нас 11 дней, но 21 день) 12 дней, но 22 дня 
А так как я ниже делаю Switch для остатка на деление - просто вынес эти 4 дня в исключение

2023-07-09 11:09 UTC, DanteIT94 commented on ToDoTracker/TrackerCreationViewFolder/TrackerTypeViewController.swift
> +        //        nonRegularEventButton.addTarget(nil, action: #selector(nonRegularEventButtonTapped), for: .touchUpInside)
исправлено - ранее не добавлял так как в ТЗ вроде как не было такой задачи (думал что дальше будем реализовывать)

2023-07-09 11:11 UTC, DanteIT94 commented on ToDoTracker/TrackerCreationViewFolder/ScheduleFolder/SwitchCell.swift
> +    func switchCellDidToggle(_ cell: SwitchCell, isOn: Bool)
А Вы не могли бы подсказать для чего его туда выносить?

2023-07-09 11:11 UTC, DanteIT94 commented on ToDoTracker/TrackerCreationViewFolder/ScheduleFolder/ScheduleViewController.swift
> +//import UIKit
Сделано!

2023-07-09 11:11 UTC, DanteIT94 commented on ToDoTracker/TrackerCreationViewFolder/CategoryFolder/CategoryCell.swift
> +//    private let arrowImageView: UIImageView = {
сделано!

2023-07-09 11:13 UTC, DanteIT94 commented on ToDoTracker/Models/Tracker.swift
> +    ///Можно ли заменить на UUID?
Удалил

2023-07-09 11:18 UTC, DanteIT94 commented on ToDoTracker/Helpers/MockHelpers .swift
> +                Tracker(id: UUID(), name: "Этил", color: .colorSection5 ?? .green, emoji: "❤️", schedule: [0, 1, 2, 3, 4, 5, 6, 7]),
Эх, когда же уже получиться видеть возможности для использования "синтаксических" лазеек((

2023-07-09 11:19 UTC, DanteIT94 commented on ToDoTracker/TabBar/TabBarViewConroller.swift
> +        tabBar.tintColor = .white
Исправлено!

2023-07-09 12:01 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/ScheduleFolder/SwitchCell.swift
> +    func switchCellDidToggle(_ cell: SwitchCell, isOn: Bool)
Ну он используется как публичный и к нему есть доступ вне области видимости класса

2023-07-10 07:10 UTC, DanteIT94 commented on ToDoTracker/TabBar/TabBarViewConroller.swift
> +
исправлено!

2023-07-10 08:53 UTC, protos17 approved these changes

2023-07-10 08:53 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/NewHabitCreation/NewHabitViewController.swift
> +           choosedDays.isEmpty == false {
Здесь тоже можно заменить на:

!choosedDays.isEmpty

2023-07-10 08:53 UTC, protos17 commented on ToDoTracker/TrackerCreationViewFolder/NewHabitCreation/NewHabitViewController.swift
> +            print("Delegate is not set")
Лишние принты рекомендую поубирать

2023-07-10 14:51 UTC, merged